//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_Myrtle.Citrus {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapDBResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapDBResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp_Myrtle.Citrus.MapDBResource", typeof(MapDBResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 master 的本地化字符串。
        /// </summary>
        internal static string _IndexTableDefaultBDB {
            get {
                return ResourceManager.GetString("_IndexTableDefaultBDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MDB-MANIFEST 的本地化字符串。
        /// </summary>
        internal static string _IndexTableName {
            get {
                return ResourceManager.GetString("_IndexTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select count(&quot;a_index&quot;) from &quot;{0}&quot; where &quot;a_database&quot; = @A_DATABASE and &quot;a_key&quot; = @A_KEY; 的本地化字符串。
        /// </summary>
        internal static string ContainsIndexTable_sql {
            get {
                return ResourceManager.GetString("ContainsIndexTable_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from &quot;{0}&quot;; 的本地化字符串。
        /// </summary>
        internal static string Get_sql {
            get {
                return ResourceManager.GetString("Get_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select &quot;a_data_table&quot; from &quot;{0}&quot; where &quot;a_database&quot; = @A_DATABASE and &quot;a_key&quot; = @A_KEY; 的本地化字符串。
        /// </summary>
        internal static string GetDataTable_sql {
            get {
                return ResourceManager.GetString("GetDataTable_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select &quot;a_data_type&quot; from &quot;{0}&quot; where &quot;a_database&quot; = @A_DATABASE and &quot;a_key&quot; = @A_KEY; 的本地化字符串。
        /// </summary>
        internal static string GetType_sql {
            get {
                return ResourceManager.GetString("GetType_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into &quot;{0}&quot;(&quot;b_data&quot;) values (@B_DATA); 的本地化字符串。
        /// </summary>
        internal static string InsertDataType_sql {
            get {
                return ResourceManager.GetString("InsertDataType_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into &quot;{0}&quot;(&quot;a_database&quot;,&quot;a_key&quot;, &quot;a_data_table&quot;, &quot;a_data_type&quot;) values (@A_DATABASE,@A_KEY,@A_DATA_TABLE,@A_DATA_TYPE); 的本地化字符串。
        /// </summary>
        internal static string InsertIndexTable_sql {
            get {
                return ResourceManager.GetString("InsertIndexTable_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create table if not exists &quot;{0}&quot;(&quot;b_index&quot; integer not null unique primary key autoincrement ,&quot;b_data&quot; blob); 的本地化字符串。
        /// </summary>
        internal static string NeoDataTable_sql {
            get {
                return ResourceManager.GetString("NeoDataTable_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create table if not exists &quot;{0}&quot;(&quot;a_index&quot; integer not null unique primary key autoincrement,&quot;a_database&quot; varchar(500) not null default &apos;master&apos;,&quot;a_key&quot; varchar(500) not null,&quot;a_data_table&quot; varchar(50) not null ,&quot;a_data_type&quot; int not null default &apos;1&apos;,&quot;a_time&quot; timestamp default current_timestamp); 的本地化字符串。
        /// </summary>
        internal static string NeoIndexTable_sql {
            get {
                return ResourceManager.GetString("NeoIndexTable_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 drop table &quot;{0}&quot;; 的本地化字符串。
        /// </summary>
        internal static string RemoveDataTable_sql {
            get {
                return ResourceManager.GetString("RemoveDataTable_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from &quot;{0}&quot; where &quot;a_database&quot; = @A_DATABASE and &quot;a_key&quot; = @A_KEY; 的本地化字符串。
        /// </summary>
        internal static string RemoveIndex_sql {
            get {
                return ResourceManager.GetString("RemoveIndex_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update &quot;{0}&quot; set &quot;a_data_table&quot; = @A_DATA_TABLE where &quot;a_database&quot; = @A_DATABASE and &quot;a_key&quot; = @A_KEY; 的本地化字符串。
        /// </summary>
        internal static string UpdateIndexDataTable_sql {
            get {
                return ResourceManager.GetString("UpdateIndexDataTable_sql", resourceCulture);
            }
        }
    }
}
